### PR TITLE
Download dialogue box

### LINKED ISSUE #51: Create a download dialog box for naming file download.
### Description

On click of the download button, automatically downloads as test.zip. 

### Steps to Reproduce

1. Click download.

**Expected behavior:** 
Should ask what the file should be named.

**Actual behavior:**
Downloads as test.zip.

**Reproduces how often:**
100%

### System version

macOS Sierra 10.12.5

### PR DESCRIPTION
**Pull request by samwincott**
I hope this is what you were looking for! 
resolves #51

### CODE REVIEW

File: hackIDE/static/hackIDE/js/custom.js [hunk 1]
```diff
@@ -210,7 +210,13 @@ $(document).ready(function(){
 		var zip = new JSZip()
 		zip.file(filename+"."+ext, text)
 		var downloaded = zip.generate({type : "blob"})
-		saveAs(downloaded, "test.zip")
+
+		var user_filename_choice = prompt("Enter a filename for the .zip", "filename")
```
Comment (sahildua2305) [inline hackIDE/static/hackIDE/js/custom.js]: I think it should be `filename` instead of `"filename"`.

Comment (samwincott) [inline hackIDE/static/hackIDE/js/custom.js]: Good thinking, will update

File: hackIDE/static/hackIDE/js/custom.js [hunk 2]
```diff
@@ -210,7 +210,13 @@ $(document).ready(function(){
 		var zip = new JSZip()
 		zip.file(filename+"."+ext, text)
 		var downloaded = zip.generate({type : "blob"})
-		saveAs(downloaded, "test.zip")
+
+		var user_filename_choice = prompt("Enter a filename for the .zip", filename)
+		if (user_filename_choice == null || user_filename_choice == "" || user_filename_choice == " " ){
```
Comment (sahildua2305) [inline hackIDE/static/hackIDE/js/custom.js]: Why are you checking for `" "` here? Why not for `"  "` (2 or more spaces) as well?

I'd say a better approach will be to strip all leading/trailing spaces and check if there's any character left.

Also, I'd like to see a variable (may be `filename`) being set in if/else statements and that being used below for `saveAs` command. Basically, I'd like to see `saveAs` only once because that will make it easy to make any other logical changes in future. What's your opinion about this?

Nit: Indentation inside if/else statements also needs to be fixed.

Comment (samwincott) [inline hackIDE/static/hackIDE/js/custom.js]: I agree, I can do it now
